version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: plat_agri
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestjs_app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: 123456
      DB_DATABASE: plat_agri
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  pgdata:
